services:
  app:
    build:
      context: ..
      dockerfile: tools/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ../.env

volumes:
  mongo_data:
    driver: local